<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists

# you can free to change all these codes/structure
# here A and B are list of lists


def matrix_mul(A, B):
  """
  Returns the product of those two matrices 
  """

  # verifing the input matrix eligible for multiplication
  if (len(A[0]) == len(B)):
    
    # creating resultant list with zeros based on the input size
    multiplication_of_A_and_B = [[0 for colmns in range(len(B[0]))] for rows in range(len(A))]
      
    # to iterate over rows of A
    for i in range(len(A)):

      # to iterate over columns of B
      for j in range(len(B[0])):

        # to iterate over rows of B
        for k in range(len(B)):

          # each iteration data captured
          multiplication_of_A_and_B[i][j] += A[i][k]*B[k][j]

    return print(*(multiplication_of_A_and_B),sep="\n")
  
  else:
    return print("Matrix Multiplication not possible")

#input matricx A and B
A = [[1,2],[3,4]]
B = [[1,2,3,4,5],[5,6,7,8,9]]
matrix_mul(A, B)

[11, 14, 17, 20, 23]
[23, 30, 37, 44, 51]


<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

#video link for the topic - https://www.appliedaicourse.com/lecture/11/applied-machine-learning-online-course/2876/proportional-sampling/2/module-2-data-science-exploratory-data-analysis-and-data-visualization
# you can free to change all these codes/structure


def pick_a_number_from_list(A):
    """
    for picking an element from with the probability propotional to its magnitude.
    """
    # creating a r.v with sum of all emenents in list A.
    s = 0
    for i in A:
      s += i

    # create a new list with normalizing the values from the list A using SUM.
    d = []
    for f in A:
      d.append(f/s)

    # create a new list with cumulative normalized sum.
    dd =[]
    k = 0
    for j in d:
      k += j
      dd.append(k)

    r = uniform(0,1) #unifor r.v 0 to 1

    # return number proportional to its magnitude
    for l in range(len(A)):
      if r <= dd[l]:
        return (A[l])


    #return #selected_random_number

def sampling_based_on_magnitued():
    """
    returns elements with proportinal sampling
    """
    
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        numbers.append(number)
    return print("Elements from the list A selected randomly with probability proportional to its magnitudefor 100 times with replacement.\n",numbers,"\n")


A = [0,5,27,6,13,28,100,45,10,79]
numbers=[]
sampling_based_on_magnitued()

A = sorted(A)
for n in A:
  print("frequency of number",n,"is",numbers.count(n))

Elements from the list A selected randomly with probability proportional to its magnitudefor 100 times with replacement.
 [28, 45, 79, 100, 45, 27, 79, 79, 79, 5, 27, 100, 10, 100, 100, 45, 79, 79, 79, 28, 28, 79, 28, 79, 5, 79, 100, 13, 45, 28, 100, 79, 79, 6, 28, 100, 45, 100, 28, 79, 45, 100, 10, 100, 28, 100, 45, 27, 45, 100, 100, 79, 28, 79, 10, 10, 28, 27, 79, 79, 27, 79, 27, 100, 100, 45, 10, 100, 79, 13, 79, 79, 79, 100, 79, 100, 100, 79, 100, 100, 100, 100, 79, 10, 100, 28, 27, 28, 100, 100, 100, 100, 27, 100, 27, 79, 100, 79, 100] 

frequency of number 0 is 0
frequency of number 5 is 2
frequency of number 6 is 1
frequency of number 10 is 6
frequency of number 13 is 2
frequency of number 27 is 9
frequency of number 28 is 12
frequency of number 45 is 9
frequency of number 79 is 27
frequency of number 100 is 31


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program

def replace_digits(String):
    # write your code

    # new_str to capture string after removing non digits. 
    new_str = re.findall("[0-9]", String)
    
    return('#'*len(new_str)) # modified string which is after replacing the # with digits

replace_digits(input("Enter a strong to remove all the not digits and replace the digits with #: "))

Enter a strong to remove all the not digits and replace the digits with #: #2a$#b%c%561#


'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    
    # mapping to list to form dictonaries 
    mappDict = dict(zip(students, marks))

    # write code for computing top top 5 students
    top_5_students = sorted([(key,value) for (value,key) in mappDict.items()], reverse = True)[:5]

    # write code for computing top least 5 students
    least_5_students = sorted([(key,value) for (value,key) in mappDict.items()])[:5]

    # write code for computing students in range 25 and 75
    diff = (len(Marks)-1)
    
    #the index of 25th percentile is 
    low_q = 0.25*diff

    # round the index value to floor integer value
    for l in reversed(range(diff)):
      if l <= low_q:
        low_q_index = l
        break

    # index of 75th percentile is
    up_q = 0.75*diff

    # round the index value to ceil integer value
    for l in range(diff):
      if l >= up_q:
        up_q_index = l
        break

    students_within_25_and_75 = sorted([(key,value) for (value,key) in mappDict.items()])[low_q_index:up_q_index]
    
    return (print("\na. Top 5 students",*top_5_students, "\nb. Least 5 students",*least_5_students,"\nc. Students within 25 and 75",*students_within_25_and_75,sep="\n"))


# Input data
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]

display_dash_board(Students, Marks)


a. Top 5 students
(98, 'student8')
(80, 'student10')
(78, 'student2')
(48, 'student5')
(47, 'student7')

b. Least 5 students
(12, 'student3')
(14, 'student4')
(22, 'student9')
(43, 'student6')
(45, 'student1')

c. Students within 25 and 75
(22, 'student9')
(43, 'student6')
(45, 'student1')
(47, 'student7')
(48, 'student5')


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [ ]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here

    # Create another D list with distance form P respectively w.r.t S
    D = []

    # update D with the distance of each point betweeb S and P
    for f in S:
      (x,y) = f
      (p,q) = P
      import math
      nu = ((x*p)+(y*q))
      de = (math.sqrt((x**2)+(y**2)))*(math.sqrt((p**2)+(q**2)))
      re = (nu/de)
      fn = round(math.acos(re),3)
      D.append(fn)

    distan = dict(zip(S,D))

    closest_points_to_p = list(dict(sorted([(key,value) for (value,key) in distan.items()])[:5]).values())

    return closest_points_to_p # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print("5 closest points(based on cosine distance) in S from P are ",*points,sep="\n") #print the returned values

5 closest points(based on cosine distance) in S from P are 
(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [ ]:
#import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure


def i_am_the_one(red,blue,line):
    '''
    returns Yes or NO for input line if it seperates all the red points 
    from blue points
    '''
    # convert string to list of# float
    line = line.replace('x','+').replace('y','+').split('+')
    line = [x for x in line if x]

    #create a r.v to capture the outcome of eact red poit w.r.t line
    validate=[]

    # for loop to iterate through all the red points and extracy (x,y)
    for i in range(len(red)):
        x1,y1 = red[i]

        # AX1+BY1+C for each RED point
        point_R = ((float(line[0])*x1)+(float(line[1])*y1)+float(line[2]))

        # YES if point is above the line
        if (point_R > 0):
          validate.append("yes")
        else:
          validate.append("no")

    # for loop to iterate through all the Blue points and extracy (x,y)
    for e in range(len(blue)):
        x2,y2 = blue[e]

        # AX2+BY2+C for each BLUE point
        point_B = ((float(line[0])*x2)+(float(line[1])*y2)+float(line[2]))

        # YES if point is below the line
        if (point_B < 0):
          validate.append("yes")
        else:
          validate.append("no")

    # To check if all the values in the les are YES
    validated = all(element == validate[0] for element in validate)
  
    if (validated):
        return 'yes'
    else:
        return 'no'

    #return #yes/no

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

yes
no
no
yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results
# you can free to change all these codes/structure


def curve_smoothing(string):
    # your code
    # Create a list from the input string 
    str_lst = string.replace(' ','').split(',')
    #print(str_lst)

    # create a list with values containaig indices of the numbers present in str_lst'
    n_lst = []
    for indx,element in enumerate(str_lst):
      if element != '_':
        n_lst.append(indx)
    #print(n_lst)

    # strings starting with missing values i.e '_'
    if n_lst[0] != 0:
      n_lst = [-1] + n_lst # concatenate list
    #print(n_lst)

    # strings ending with missing values
    if n_lst[-1] != (len(str_lst)-1):
      n_lst = n_lst + [-1] 
    #print(n_lst)

    # For loop string with numbers in between or on number present at initial and end
    # require pair of index to determine the gap and index at which number is present
    for initial,final in zip(n_lst[:-1], n_lst[1:]):
      #print(initial,final)

      # if strings starting with missing values
      if initial == -1:
        value = float(str_lst[final])/(final+1) #divide value w.r.t number of blanks

        # updating str_lst with obtained value in the blanks
        # and since initial is -1
        for j in range((initial+1),(final+1)):
          str_lst[j] = value

      # if strings end with missing values
      elif final == -1:
        value = float(str_lst[initial])/((len(str_lst))-initial) #divide value w.r.t number of blanks

        # updating str_lst with obtained value in the blanks
        for j in range(initial,len(str_lst)):
          str_lst[j] = value

      else:
        value = (float(str_lst[initial])+float(str_lst[final]))/(final-initial+1)
        for j in range(initial, final+1):
          str_lst[j] = value
     
    return str_lst#list of values

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)# print above values

[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code


# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    '''
    computes conditional probablites
    '''
    # from the given question 
    F = ['F1','F2','F3','F4','F5']
    S = ['S1','S2','S3']
    indx = ['a.','b.','c.','d.','e.'] 

    f = []
    s = []
    v = []

    # to iterate over all elements in F and S
    for i in F:
      for j in S:
        prob_f = 0
        prob_s = 0
        for k in range(len(A)):
          if(A[k][1]==j):
            prob_s += 1
            if(A[k][0]==i):
              prob_f += 1

        
        if j == 'S1':
          print(indx[F.index(i)], end=' ')

        if j == 'S1' or j == 'S2':
          print('P(F={}|S=={})={}/{},'.format(i, j, prob_f, prob_s),end=' ')

        if j == 'S3':
          print('P(F={}|S=={})={}/{}'.format(i, j, prob_f, prob_s),end='\n')
          #print(end='\n')

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    '''
    a. Number of common words between S1, S2
    b. Words in S1 but not in S2
    c. Words in S2 but not in S1
    '''
    # conver list to SET to perform Intersection and difference operation
    set_S1 = set(S1.split())
    set_S2 = set(S2.split())

    a = len(set_S1 & set_S2) # A intersection B
    b = list(set_S1 - set_S2) # A Diff B
    c = list(set_S2 - set_S1) # B Diff A

    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print('a.',a,'\nb.',b,'\nc.',c)#the above values

a. 7 
b. ['first', '5', 'F'] 
c. ['second', '3', 'S']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure

import math #to compute log10

def compute_log_loss(A):
    '''
    returns log loss calculated value 
    '''
    loss_sum = 0 #capture sum part of log_loss function
    for i in range(len(A)):
        y = A[i][0]
        y_score = A[i][1]
        loss_sum += (y*math.log10(y_score))+((1-y)*math.log10((1-y_score)))

    loss = ((-1/8)*loss_sum)
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(round(loss,7))# the above loss

0.4243099
